---
kind: pipeline
# type: ssh
name: build-equipment-leasing-admin

clone:
  disable: true

# server:
#   host: 49.232.194.85
#   user: root
#   password: Dq990821

steps:
  # - name: ssh-run
  #   commands:
  #     - pwd
  #     - git --version
  #     - docker pull vuejs/ci
  #     - docker pull nginx
  #     - docker-compose -f docker/docker-compose-drone.yml down -v --rmi local
  #     - docker-compose -f docker/docker-compose-drone.yml up -d

  - name: dingtalk-send
    image: lddsb/drone-dingtalk-message
    settings:
      token: 8a3d317d8368c806ef071e7db17e0ad462f0ac6b4dc2114070067ab2433950a7
      type: markdown
      tpl: http://49.232.194.85:9001/test/tpl.md?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=minio%2F20201008%2F%2Fs3%2Faws4_request&X-Amz-Date=20201008T154015Z&X-Amz-Expires=432000&X-Amz-SignedHeaders=host&X-Amz-Signature=5b65cacd8132b936b6c58db2b9e4844f4a0011482d8a3482288ca5897e678b6a
      secret: SECaa58a0deccd7b1bd30f88a2e17ccba4f7e26543c7643b7b468ecc099c93c49f2
