---
kind: pipeline
name: build-equipment-leasing-admin

# steps:
# - name: docker-push
#   image: plugins/docker
#   settings:
#     username: dengqing
#     password: dengqing0821
#     repo: dengqing/drone-test
#     dockerfile: docker/Dockerfile
# ---
# - name: ssh commands
#   image: appleboy/drone-ssh
#   settings:
#     host: 49.232.194.85
#     username: root
#     password: Dq990821
#     port: 22
#     script:
#       - pwd
#       - ls -al
#       - ls docker -al
#       - docker-compose -f docker/docker-compose-drone.yml up -d

clone:
  disable: true

steps:
  # - name: run
  #   commands:
  #     - pwd
  #     - git --version
  #     - docker pull vuejs/ci
  #     - docker pull nginx
  #     - docker-compose -f docker/docker-compose-drone.yml down -v --rmi local
  #     - docker-compose -f docker/docker-compose-drone.yml up -d
  # https://oapi.dingtalk.com/robot/send?access_token=8a3d317d8368c806ef071e7db17e0ad462f0ac6b4dc2114070067ab2433950a7
  - name: dingtalk
    image: lddsb/drone-dingtalk-message
    settings:
      token: 8a3d317d8368c806ef071e7db17e0ad462f0ac6b4dc2114070067ab2433950a7
      type: markdown
      message_color: true
      tpl: ./tpl.md
      secret: SECaa58a0deccd7b1bd30f88a2e17ccba4f7e26543c7643b7b468ecc099c93c49f2
