---
kind: pipeline
type: ssh
name: build-equipment-leasing-admin

server:
  host: 49.232.194.85
  user: root
  password: Dq990821

steps:
  - name: ssh-run
    commands:
      - pwd
      - git --version
      - docker pull vuejs/ci
      - docker pull nginx
      - docker-compose -f docker/docker-compose-drone.yml down -v --rmi local
      - docker-compose -f docker/docker-compose-drone.yml up -d

  steps:
    - name: dingtalk
      image: lddsb/drone-dingtalk-message
      settings:
        token: 8a3d317d8368c806ef071e7db17e0ad462f0ac6b4dc2114070067ab2433950a7
        type: markdown
        tpl: tpl.md
        secret: SECaa58a0deccd7b1bd30f88a2e17ccba4f7e26543c7643b7b468ecc099c93c49f2
