---
kind: pipeline
type: ssh
name: build-equipment-leasing-admin

# steps:
# - name: docker-push
#   image: plugins/docker
#   settings:
#     username: dengqing
#     password: dengqing0821
#     repo: dengqing/drone-test
#     dockerfile: docker/Dockerfile
# ---
# - name: ssh commands
#   image: appleboy/drone-ssh
#   settings:
#     host: 49.232.194.85
#     username: root
#     password: Dq990821
#     port: 22
#     script:
#       - pwd
#       - ls -al
#       - ls docker -al
#       - docker-compose -f docker/docker-compose-drone.yml up -d

server:
  host: 49.232.194.85
  user: root
  password: Dq990821

steps:
  - name: run
    commands:
      - pwd
      - git --version
      - docker pull vuejs/ci
      - docker pull nginx
      - docker-compose -f docker/docker-compose-drone.yml down -v
      - docker-compose -f docker/docker-compose-drone.yml up -d
