---
kind: pipeline
type: ssh
name: build-equipment-leasing-admin

server:
  host: 49.232.194.85
  user: root
  password: Dq990821

steps:
  - name: ssh-run
    commands:
      - pwd
      - git --version
      - docker pull vuejs/ci
      - docker pull nginx
      - docker-compose -f docker/docker-compose-drone.yml down -v --rmi local
      - docker-compose -f docker/docker-compose-drone.yml up -d
      - curl https://sc.ftqq.com/SCU2561.send?text=部署成功
