version: '3'

services:
  redis:
    image: redis
    volumes:
      - redis_db_data:/data/ela/redis
    restart: always
    
  mongo:
      image: mongo
      restart: always
      volumes: 
        - mongo_db_data:/data/ela/mongo
  
  ela: 
    depends_on: 
      - redis
      - mongo
    image: ela
    restart: always
    volumes: 
      - /data/equipment-leasing-ela:/data/equipment-leasing-ela
    ports: 
      - 80:80
      - 443:443
      - 43554:43554
    environment: 
      MONGO_HOST: mongo
      REDIS_HOST: redis
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8888:8081



volumes: 
  redis_db_data: 
  mongo_db_data: