version: "3.8"

services:
  admin:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: vue-admin
    volumes:
      - vue_admin_dist:/app/dist

volumes:
  vue_admin_dist:
    name: vue_admin_build_dist
